version: 0.2
       
phases:
  pre_build:
    commands:
      - echo Cloning submodules...
      - git submodule update --init
  build:
    commands:
      - echo Generating build files...
      - cmake -H. -B"/tmp/build" -G"Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/tmp/build  -DSecp256k1_ROOT_DIR=/usr/local -DENABLE_MONGODB_SUPPORT=ON
      - echo Building...
      - ninja -C /tmp/build -j$(nproc) all
  post_build:
    commands:
      - echo Runing `tests`
      - ninja -C /tmp/build test
