version: 0.2
       
phases:
  pre_build:
    commands:
      - echo Cloning submodules...
      - git submodule update --init
  build:
    commands:
      - echo Generating build files...
      - mkdir build && cd build
      - cmake ../ -G"Ninja" -DCMAKE_BUILD_TYPE=Release -DSecp256k1_ROOT_DIR=/usr/local -DENABLE_MONGODB_SUPPORT=ON -DENABLE_BIND_LIBRARIES=ON
      - echo Building...
      - ninja -j$(nproc) all
  post_build:
    commands:
      - echo Runing tests
      - ninja test
